source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'BBAPainterDemo_Example' do
  pod 'BBAPainterDemo', :path => '../'
  pod 'SDWebImage', '~> 4.0'
  
  target 'BBAPainterDemo_Tests' do
    inherit! :search_paths
    
    
  end
end
