//
//  BBAPainterCanvasDrawView.h
//  BBAPainterDemo
//
//  Created by Ning,Liujie on 2019/2/25.
//

#import "BBAPainterAsyncDrawView.h"

NS_ASSUME_NONNULL_BEGIN

@interface BBAPainterCanvasDrawView : BBAPainterAsyncDrawView

/* When positive, the background of the layer will be drawn with
 * rounded corners. Also effects the mask generated by the
 * `masksToBounds' property. Defaults to zero. Animatable. */
@property (nonatomic, assign) CGFloat cornerRadius;

/* The width of the layer's border, inset from the layer bounds. The
 * border is composited above the layer's content and sublayers and
 * includes the effects of the `cornerRadius' property. Defaults to
 * zero. Animatable. */
@property (nonatomic, assign) CGFloat borderWidth;

/* The color of the layer's border. Defaults to opaque black. Colors
 * created from tiled patterns are supported. Animatable. */
@property (nonatomic, strong) UIColor *borderColor;

/** Shadow properties. **/

/* The color of the shadow. Defaults to opaque black. Colors created
 * from patterns are currently NOT supported. Animatable. */
@property (nonatomic, strong) UIColor *shadowColor;

/* The shadow offset. Defaults to (0, -3). Animatable. */
@property (nonatomic, assign) UIOffset shadowOffset;

@property (nonatomic, assign) CGFloat shadowBlur;

@property (nonatomic, strong) UIImage *backgroundImage;

@end

NS_ASSUME_NONNULL_END
